### ISSUE TITLE
any plan to work further to make it vue v1 + latest materialize compatible?

### ISSUE THREAD

**Issue by auvipy** [paulpflug/vue-materialize#1]

**Comment by paulpflug** [comment]
There are plans. I have already invested further work, but it will take a 
while especially documentation 😀

Am 25. November 2015 11:18:34 schrieb Asif Saifuddin Auvi 
notifications@github.com:

**Comment by auvipy** [comment]
awesome!

**Comment by paulpflug** [comment]
Hey,
I added a few components and made it v1 compatible

still far from finished ;) especially the documentation
