### ISSUE TITLE
Installing vue-materialize fails

### ISSUE THREAD

**Issue by Jabari** [paulpflug/vue-materialize#5]
`No compatible version found: vue-collapsible@^1.1.0`
<img width="827" alt="screen shot 2016-09-20 at 3 46 59 pm" src="https://cloud.githubusercontent.com/assets/1389770/18691612/88ca64ec-7f49-11e6-9284-74075010b228.png">

**Comment by Jabari** [comment]
@paulpflug The latest version of vue-collapsible is 1.0.1

**Comment by paulpflug** [comment]
ok, this should work now. Strangely the publishing didn't work the first time

thanks for reporting :+1:

**Comment by Jabari** [comment]
thanks @paulpflug!
